//! Tool types for building/editing

use super::building::BuildingType;
use std::fmt;

/// Available tools
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Tool {
    Select,
    Bulldoze,
    Path,
    Queue,
    
    // Trees
    TreeOak,
    TreeMaple,
    TreeBirch,
    TreeWillow,
    TreePine,
    TreePalm,
    TreeBamboo,
    TreeTropical,
    TreeCherry,
    TreeMagnolia,
    BushHedge,
    BushFlowering,
    TopiaryBall,
    TopiarySpiral,
    TopiaryAnimal,
    FlowersBed,
    FlowersPlanter,
    FlowersHanging,
    FlowersWild,
    GroundCover,
    
    // Path Furniture
    BenchWooden,
    BenchMetal,
    LampVictorian,
    LampModern,
    TrashCanBasic,
    TrashCanFancy,
    
    // Food
    FoodHotdog,
    FoodBurger,
    FoodFries,
    FoodPretzel,
    FoodIcecream,
    DrinkSoda,
    DrinkLemonade,
    DrinkCoffee,
    SnackPopcorn,
    SnackNachos,
    SnackPizza,
    CartPirate,
    
    // Shops
    ShopSouvenir,
    ShopToys,
    ShopPhoto,
    ShopTicket,
    ShopPlush,
    ShopCollectibles,
    ShopCandy,
    ArcadeBuilding,
    Restroom,
    FirstAid,
    Atm,
    
    // Fountains
    FountainSmall1,
    FountainMedium1,
    FountainLarge1,
    PondSmall,

    // Theming
    ThemeCastleTower,
    ThemePirateShip,
    ThemeTempleRuins,
    ThemeHauntedTree,
    ThemeCircusTent,
    ThemeGeometric,

    // Queue Decor
    QueuePostMetal,
    QueueRope,
    QueueWaitSign,
    QueueCanopy,
    
    // Rides - Small
    RideCarousel,
    RideTeacups,
    RideBumperCars,
    RideScrambler,
    RideHauntedHouse,
    
    // Rides - Large
    RideFerrisClassic,
    RideFerrisModern,
    RideDropTower,
    RideLogFlume,
    
    // Coaster tools
    CoasterStation,
    CoasterTrackStraight,
    CoasterTrackTurnLeft,
    CoasterTrackTurnRight,
    CoasterTrackSlopeUp,
    CoasterTrackSlopeDown,
}

impl Default for Tool {
    fn default() -> Self {
        Tool::Select
    }
}

impl fmt::Display for Tool {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Tool::Select => "select",
            Tool::Bulldoze => "bulldoze",
            Tool::Path => "path",
            Tool::Queue => "queue",
            Tool::TreeOak => "tree_oak",
            Tool::TreeMaple => "tree_maple",
            Tool::TreeBirch => "tree_birch",
            Tool::TreeWillow => "tree_willow",
            Tool::TreePine => "tree_pine",
            Tool::TreePalm => "tree_palm",
            Tool::TreeBamboo => "tree_bamboo",
            Tool::TreeTropical => "tree_tropical",
            Tool::TreeCherry => "tree_cherry",
            Tool::TreeMagnolia => "tree_magnolia",
            Tool::BushHedge => "bush_hedge",
            Tool::BushFlowering => "bush_flowering",
            Tool::TopiaryBall => "topiary_ball",
            Tool::TopiarySpiral => "topiary_spiral",
            Tool::TopiaryAnimal => "topiary_animal",
            Tool::FlowersBed => "flowers_bed",
            Tool::FlowersPlanter => "flowers_planter",
            Tool::FlowersHanging => "flowers_hanging",
            Tool::FlowersWild => "flowers_wild",
            Tool::GroundCover => "ground_cover",
            Tool::BenchWooden => "bench_wooden",
            Tool::BenchMetal => "bench_metal",
            Tool::LampVictorian => "lamp_victorian",
            Tool::LampModern => "lamp_modern",
            Tool::TrashCanBasic => "trash_can_basic",
            Tool::TrashCanFancy => "trash_can_fancy",
            Tool::FoodHotdog => "food_hotdog",
            Tool::FoodBurger => "food_burger",
            Tool::FoodFries => "food_fries",
            Tool::FoodPretzel => "food_pretzel",
            Tool::FoodIcecream => "food_icecream",
            Tool::DrinkSoda => "drink_soda",
            Tool::DrinkLemonade => "drink_lemonade",
            Tool::DrinkCoffee => "drink_coffee",
            Tool::SnackPopcorn => "snack_popcorn",
            Tool::SnackNachos => "snack_nachos",
            Tool::SnackPizza => "snack_pizza",
            Tool::CartPirate => "cart_pirate",
            Tool::ShopSouvenir => "shop_souvenir",
            Tool::ShopToys => "shop_toys",
            Tool::ShopPhoto => "shop_photo",
            Tool::ShopTicket => "shop_ticket",
            Tool::ShopPlush => "shop_plush",
            Tool::ShopCollectibles => "shop_collectibles",
            Tool::ShopCandy => "shop_candy",
            Tool::ArcadeBuilding => "arcade_building",
            Tool::Restroom => "restroom",
            Tool::FirstAid => "first_aid",
            Tool::Atm => "atm",
            Tool::FountainSmall1 => "fountain_small_1",
            Tool::FountainMedium1 => "fountain_medium_1",
            Tool::FountainLarge1 => "fountain_large_1",
            Tool::PondSmall => "pond_small",
            Tool::ThemeCastleTower => "theme_castle_tower",
            Tool::ThemePirateShip => "theme_pirate_ship",
            Tool::ThemeTempleRuins => "theme_temple_ruins",
            Tool::ThemeHauntedTree => "theme_haunted_tree",
            Tool::ThemeCircusTent => "theme_circus_tent",
            Tool::ThemeGeometric => "theme_geometric",
            Tool::QueuePostMetal => "queue_post_metal",
            Tool::QueueRope => "queue_rope",
            Tool::QueueWaitSign => "queue_wait_sign",
            Tool::QueueCanopy => "queue_canopy",
            Tool::RideCarousel => "ride_carousel",
            Tool::RideTeacups => "ride_teacups",
            Tool::RideBumperCars => "ride_bumper_cars",
            Tool::RideScrambler => "ride_scrambler",
            Tool::RideHauntedHouse => "ride_haunted_house",
            Tool::RideFerrisClassic => "ride_ferris_classic",
            Tool::RideFerrisModern => "ride_ferris_modern",
            Tool::RideDropTower => "ride_drop_tower",
            Tool::RideLogFlume => "ride_log_flume",
            Tool::CoasterStation => "coaster_station",
            Tool::CoasterTrackStraight => "coaster_track_straight",
            Tool::CoasterTrackTurnLeft => "coaster_track_turn_left",
            Tool::CoasterTrackTurnRight => "coaster_track_turn_right",
            Tool::CoasterTrackSlopeUp => "coaster_track_slope_up",
            Tool::CoasterTrackSlopeDown => "coaster_track_slope_down",
        };
        write!(f, "{}", name)
    }
}

impl Tool {
    /// Parse tool from string
    pub fn from_string(s: &str) -> Option<Tool> {
        match s {
            "select" => Some(Tool::Select),
            "bulldoze" => Some(Tool::Bulldoze),
            "path" => Some(Tool::Path),
            "queue" => Some(Tool::Queue),
            "tree_oak" => Some(Tool::TreeOak),
            "tree_maple" => Some(Tool::TreeMaple),
            "tree_birch" => Some(Tool::TreeBirch),
            "tree_willow" => Some(Tool::TreeWillow),
            "tree_pine" => Some(Tool::TreePine),
            "tree_palm" => Some(Tool::TreePalm),
            "tree_bamboo" => Some(Tool::TreeBamboo),
            "tree_tropical" => Some(Tool::TreeTropical),
            "tree_cherry" => Some(Tool::TreeCherry),
            "tree_magnolia" => Some(Tool::TreeMagnolia),
            "bush_hedge" => Some(Tool::BushHedge),
            "bush_flowering" => Some(Tool::BushFlowering),
            "topiary_ball" => Some(Tool::TopiaryBall),
            "topiary_spiral" => Some(Tool::TopiarySpiral),
            "topiary_animal" => Some(Tool::TopiaryAnimal),
            "flowers_bed" => Some(Tool::FlowersBed),
            "flowers_planter" => Some(Tool::FlowersPlanter),
            "flowers_hanging" => Some(Tool::FlowersHanging),
            "flowers_wild" => Some(Tool::FlowersWild),
            "ground_cover" => Some(Tool::GroundCover),
            "bench_wooden" => Some(Tool::BenchWooden),
            "bench_metal" => Some(Tool::BenchMetal),
            "lamp_victorian" => Some(Tool::LampVictorian),
            "lamp_modern" => Some(Tool::LampModern),
            "trash_can_basic" => Some(Tool::TrashCanBasic),
            "trash_can_fancy" => Some(Tool::TrashCanFancy),
            "food_hotdog" => Some(Tool::FoodHotdog),
            "food_burger" => Some(Tool::FoodBurger),
            "food_fries" => Some(Tool::FoodFries),
            "food_pretzel" => Some(Tool::FoodPretzel),
            "food_icecream" => Some(Tool::FoodIcecream),
            "drink_soda" => Some(Tool::DrinkSoda),
            "drink_lemonade" => Some(Tool::DrinkLemonade),
            "drink_coffee" => Some(Tool::DrinkCoffee),
            "snack_popcorn" => Some(Tool::SnackPopcorn),
            "snack_nachos" => Some(Tool::SnackNachos),
            "snack_pizza" => Some(Tool::SnackPizza),
            "cart_pirate" => Some(Tool::CartPirate),
            "shop_souvenir" => Some(Tool::ShopSouvenir),
            "shop_toys" => Some(Tool::ShopToys),
            "shop_photo" => Some(Tool::ShopPhoto),
            "shop_ticket" => Some(Tool::ShopTicket),
            "shop_plush" => Some(Tool::ShopPlush),
            "shop_collectibles" => Some(Tool::ShopCollectibles),
            "shop_candy" => Some(Tool::ShopCandy),
            "arcade_building" => Some(Tool::ArcadeBuilding),
            "restroom" => Some(Tool::Restroom),
            "first_aid" => Some(Tool::FirstAid),
            "atm" => Some(Tool::Atm),
            "fountain_small_1" => Some(Tool::FountainSmall1),
            "fountain_medium_1" => Some(Tool::FountainMedium1),
            "fountain_large_1" => Some(Tool::FountainLarge1),
            "pond_small" => Some(Tool::PondSmall),
            "theme_castle_tower" => Some(Tool::ThemeCastleTower),
            "theme_pirate_ship" => Some(Tool::ThemePirateShip),
            "theme_temple_ruins" => Some(Tool::ThemeTempleRuins),
            "theme_haunted_tree" => Some(Tool::ThemeHauntedTree),
            "theme_circus_tent" => Some(Tool::ThemeCircusTent),
            "theme_geometric" => Some(Tool::ThemeGeometric),
            "queue_post_metal" => Some(Tool::QueuePostMetal),
            "queue_rope" => Some(Tool::QueueRope),
            "queue_wait_sign" => Some(Tool::QueueWaitSign),
            "queue_canopy" => Some(Tool::QueueCanopy),
            "ride_carousel" => Some(Tool::RideCarousel),
            "ride_teacups" => Some(Tool::RideTeacups),
            "ride_bumper_cars" => Some(Tool::RideBumperCars),
            "ride_scrambler" => Some(Tool::RideScrambler),
            "ride_haunted_house" => Some(Tool::RideHauntedHouse),
            "ride_ferris_classic" => Some(Tool::RideFerrisClassic),
            "ride_ferris_modern" => Some(Tool::RideFerrisModern),
            "ride_drop_tower" => Some(Tool::RideDropTower),
            "ride_log_flume" => Some(Tool::RideLogFlume),
            "coaster_station" => Some(Tool::CoasterStation),
            "coaster_track_straight" => Some(Tool::CoasterTrackStraight),
            "coaster_track_turn_left" => Some(Tool::CoasterTrackTurnLeft),
            "coaster_track_turn_right" => Some(Tool::CoasterTrackTurnRight),
            "coaster_track_slope_up" => Some(Tool::CoasterTrackSlopeUp),
            "coaster_track_slope_down" => Some(Tool::CoasterTrackSlopeDown),
            _ => None,
        }
    }
    
    /// Get the building type this tool places
    pub fn building_type(&self) -> Option<BuildingType> {
        match self {
            Tool::Select | Tool::Bulldoze | Tool::Path | Tool::Queue => None,
            Tool::CoasterStation | Tool::CoasterTrackStraight | Tool::CoasterTrackTurnLeft |
            Tool::CoasterTrackTurnRight | Tool::CoasterTrackSlopeUp | Tool::CoasterTrackSlopeDown => None,
            
            Tool::TreeOak => Some(BuildingType::TreeOak),
            Tool::TreeMaple => Some(BuildingType::TreeMaple),
            Tool::TreeBirch => Some(BuildingType::TreeBirch),
            Tool::TreeWillow => Some(BuildingType::TreeWillow),
            Tool::TreePine => Some(BuildingType::TreePine),
            Tool::TreePalm => Some(BuildingType::TreePalm),
            Tool::TreeBamboo => Some(BuildingType::TreeBamboo),
            Tool::TreeTropical => Some(BuildingType::TreeTropical),
            Tool::TreeCherry => Some(BuildingType::TreeCherry),
            Tool::TreeMagnolia => Some(BuildingType::TreeMagnolia),
            Tool::BushHedge => Some(BuildingType::BushHedge),
            Tool::BushFlowering => Some(BuildingType::BushFlowering),
            Tool::TopiaryBall => Some(BuildingType::TopiaryBall),
            Tool::TopiarySpiral => Some(BuildingType::TopiarySpiral),
            Tool::TopiaryAnimal => Some(BuildingType::TopiaryAnimal),
            Tool::FlowersBed => Some(BuildingType::FlowersBed),
            Tool::FlowersPlanter => Some(BuildingType::FlowersPlanter),
            Tool::FlowersHanging => Some(BuildingType::FlowersHanging),
            Tool::FlowersWild => Some(BuildingType::FlowersWild),
            Tool::GroundCover => Some(BuildingType::GroundCover),
            Tool::BenchWooden => Some(BuildingType::BenchWooden),
            Tool::BenchMetal => Some(BuildingType::BenchMetal),
            Tool::LampVictorian => Some(BuildingType::LampVictorian),
            Tool::LampModern => Some(BuildingType::LampModern),
            Tool::TrashCanBasic => Some(BuildingType::TrashCanBasic),
            Tool::TrashCanFancy => Some(BuildingType::TrashCanFancy),
            Tool::FoodHotdog => Some(BuildingType::FoodHotdog),
            Tool::FoodBurger => Some(BuildingType::FoodBurger),
            Tool::FoodFries => Some(BuildingType::FoodFries),
            Tool::FoodPretzel => Some(BuildingType::FoodPretzel),
            Tool::FoodIcecream => Some(BuildingType::FoodIcecream),
            Tool::DrinkSoda => Some(BuildingType::DrinkSoda),
            Tool::DrinkLemonade => Some(BuildingType::DrinkLemonade),
            Tool::DrinkCoffee => Some(BuildingType::DrinkCoffee),
            Tool::SnackPopcorn => Some(BuildingType::SnackPopcorn),
            Tool::SnackNachos => Some(BuildingType::SnackNachos),
            Tool::SnackPizza => Some(BuildingType::SnackPizza),
            Tool::CartPirate => Some(BuildingType::CartPirate),
            Tool::ShopSouvenir => Some(BuildingType::ShopSouvenir),
            Tool::ShopToys => Some(BuildingType::ShopToys),
            Tool::ShopPhoto => Some(BuildingType::ShopPhoto),
            Tool::ShopTicket => Some(BuildingType::ShopTicket),
            Tool::ShopPlush => Some(BuildingType::ShopPlush),
            Tool::ShopCollectibles => Some(BuildingType::ShopCollectibles),
            Tool::ShopCandy => Some(BuildingType::ShopCandy),
            Tool::ArcadeBuilding => Some(BuildingType::ArcadeBuilding),
            Tool::Restroom => Some(BuildingType::Restroom),
            Tool::FirstAid => Some(BuildingType::FirstAid),
            Tool::Atm => Some(BuildingType::Atm),
            Tool::FountainSmall1 => Some(BuildingType::FountainSmall1),
            Tool::FountainMedium1 => Some(BuildingType::FountainMedium1),
            Tool::FountainLarge1 => Some(BuildingType::FountainLarge1),
            Tool::PondSmall => Some(BuildingType::PondSmall),
            Tool::ThemeCastleTower => Some(BuildingType::ThemeCastleTower),
            Tool::ThemePirateShip => Some(BuildingType::ThemePirateShip),
            Tool::ThemeTempleRuins => Some(BuildingType::ThemeTempleRuins),
            Tool::ThemeHauntedTree => Some(BuildingType::ThemeHauntedTree),
            Tool::ThemeCircusTent => Some(BuildingType::ThemeCircusTent),
            Tool::ThemeGeometric => Some(BuildingType::ThemeGeometric),
            Tool::QueuePostMetal => Some(BuildingType::QueuePostMetal),
            Tool::QueueRope => Some(BuildingType::QueueRope),
            Tool::QueueWaitSign => Some(BuildingType::QueueWaitSign),
            Tool::QueueCanopy => Some(BuildingType::QueueCanopy),
            Tool::RideCarousel => Some(BuildingType::RideCarousel),
            Tool::RideTeacups => Some(BuildingType::RideTeacups),
            Tool::RideBumperCars => Some(BuildingType::RideBumperCars),
            Tool::RideScrambler => Some(BuildingType::RideScrambler),
            Tool::RideHauntedHouse => Some(BuildingType::RideHauntedHouse),
            Tool::RideFerrisClassic => Some(BuildingType::RideFerrisClassic),
            Tool::RideFerrisModern => Some(BuildingType::RideFerrisModern),
            Tool::RideDropTower => Some(BuildingType::RideDropTower),
            Tool::RideLogFlume => Some(BuildingType::RideLogFlume),
        }
    }
    
    /// Get cost of using this tool
    pub fn cost(&self) -> i32 {
        match self {
            Tool::Select => 0,
            Tool::Bulldoze => 10,
            Tool::Path => 10,
            Tool::Queue => 15,
            Tool::CoasterStation | Tool::CoasterTrackStraight | Tool::CoasterTrackTurnLeft |
            Tool::CoasterTrackTurnRight | Tool::CoasterTrackSlopeUp | Tool::CoasterTrackSlopeDown => 50,
            _ => self.building_type().map(|b| b.cost()).unwrap_or(0),
        }
    }
}
