//! Tool types for building/editing

use super::building::BuildingType;
use std::fmt;

/// Available tools
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Tool {
    Select,
    Bulldoze,
    Path,
    Queue,
    
    // Trees
    TreeOak,
    TreeMaple,
    TreeBirch,
    TreeElm,
    TreeWillow,
    TreePine,
    TreeSpruce,
    TreeFir,
    TreeCedar,
    TreeRedwood,
    TreePalm,
    TreeBanana,
    TreeBamboo,
    TreeCoconut,
    TreeTropical,
    TreeCherry,
    TreeMagnolia,
    TreeDogwood,
    TreeJacaranda,
    TreeWisteria,
    BushHedge,
    BushFlowering,
    TopiaryBall,
    TopiarySpiral,
    TopiaryAnimal,
    FlowersBed,
    FlowersPlanter,
    FlowersHanging,
    FlowersWild,
    GroundCover,
    
    // Path Furniture
    BenchWooden,
    BenchMetal,
    BenchOrnate,
    BenchModern,
    BenchRustic,
    LampVictorian,
    LampModern,
    LampThemed,
    LampDouble,
    LampPathway,
    TrashCanBasic,
    TrashCanFancy,
    TrashCanThemed,
    
    // Food
    FoodHotdog,
    FoodBurger,
    FoodFries,
    FoodCorndog,
    FoodPretzel,
    FoodIcecream,
    FoodCottonCandy,
    FoodCandyApple,
    FoodChurros,
    FoodFunnelCake,
    DrinkSoda,
    DrinkLemonade,
    DrinkSmoothie,
    DrinkCoffee,
    DrinkSlushie,
    SnackPopcorn,
    SnackNachos,
    SnackPizza,
    SnackCookies,
    SnackDonuts,
    FoodTacos,
    FoodNoodles,
    FoodKebab,
    FoodCrepes,
    FoodWaffles,
    CartPirate,
    CartSpace,
    CartMedieval,
    CartWestern,
    CartTropical,
    
    // Shops
    ShopSouvenir,
    ShopPhoto,
    ShopTicket,
    ShopEmporium,
    ShopCollectibles,
    ShopToys,
    ShopPlush,
    ShopApparel,
    ShopBricks,
    ShopRc,
    ShopCandy,
    ShopFudge,
    ShopJewelry,
    ShopPopcornShop,
    ShopSodaFountain,
    GameRingToss,
    GameBalloon,
    GameShooting,
    GameDarts,
    GameBasketball,
    ArcadeBuilding,
    VrExperience,
    PhotoBooth,
    Caricature,
    FacePaint,
    Restroom,
    FirstAid,
    Lockers,
    StrollerRental,
    Atm,
    
    // Fountains
    FountainSmall1,
    FountainSmall2,
    FountainSmall3,
    FountainSmall4,
    FountainSmall5,
    FountainMedium1,
    FountainMedium2,
    FountainMedium3,
    FountainMedium4,
    FountainMedium5,
    FountainLarge1,
    FountainLarge2,
    FountainLarge3,
    FountainLarge4,
    FountainLarge5,
    PondSmall,
    PondMedium,
    PondLarge,
    PondKoi,
    PondLily,
    SplashPad,
    WaterJets,
    MistFountain,
    InteractiveFountain,
    DancingFountain,

    // Theming
    ThemeCastleTower,
    ThemePirateShip,
    ThemeTempleRuins,
    ThemeHauntedTree,
    ThemeCircusTent,
    ThemeGeometric,

    // Queue Decor
    QueuePostMetal,
    QueueRope,
    QueueWaitSign,
    QueueCanopy,
    
    // Rides - Small
    RideKiddieCoaster,
    RideKiddieTrain,
    RideKiddiePlanes,
    RideKiddieBoats,
    RideKiddieCars,
    RideTeacups,
    RideScrambler,
    RideTiltAWhirl,
    RideSpinningApples,
    RideWhirlwind,
    RideCarousel,
    RideAntiqueCars,
    RideMonorailCar,
    RideSkyRideCar,
    RideTrainCar,
    RideBumperCars,
    RideGoKarts,
    RideSimulator,
    RideMotionTheater,
    Ride4dTheater,
    RideBumperBoats,
    RidePaddleBoats,
    RideLazyRiver,
    RideWaterPlay,
    RideSplashZone,
    RideHauntedHouse,
    RideGhostTrain,
    RideDarkRide,
    RideTunnel,
    RideThemedFacade,
    
    // Rides - Large
    RideFerrisClassic,
    RideFerrisModern,
    RideFerrisObservation,
    RideFerrisDouble,
    RideFerrisLed,
    RideDropTower,
    RideSpaceShot,
    RideObservationTower,
    RideSkySwing,
    RideStarFlyer,
    RideSwingRide,
    RideWaveSwinger,
    RideFlyingScooters,
    RideEnterprise,
    RideLoopOPlane,
    RideTopSpin,
    RideFrisbee,
    RideAfterburner,
    RideInversion,
    RideMeteorite,
    RideLogFlume,
    RideRapids,
    RideTrainStation,
    RideMonorailStation,
    RideChairlift,
    Show4d,
    ShowStunt,
    ShowDolphin,
    ShowAmphitheater,
    ShowParadeFloat,

    // Coaster Stations
    StationWooden1,
    StationWooden2,
    StationWooden3,
    StationWooden4,
    StationWooden5,
    StationSteel1,
    StationSteel2,
    StationSteel3,
    StationSteel4,
    StationSteel5,
    StationInverted1,
    StationInverted2,
    StationInverted3,
    StationInverted4,
    StationInverted5,
    StationWater1,
    StationWater2,
    StationWater3,
    StationWater4,
    StationWater5,
    StationMine1,
    StationMine2,
    StationMine3,
    StationMine4,
    StationMine5,
    StationFuturistic1,
    StationFuturistic2,
    StationFuturistic3,
    StationFuturistic4,
    StationFuturistic5,

    // Infrastructure
    ParkEntrance,
    StaffBuilding,
    
    // Coaster tools
    CoasterStation,
    CoasterTrackStraight,
    CoasterTrackTurnLeft,
    CoasterTrackTurnRight,
    CoasterTrackSlopeUp,
    CoasterTrackSlopeDown,
    CoasterTrackSlopeUpMedium,
    CoasterTrackSlopeDownMedium,
    CoasterTrackLiftHill,
    CoasterTrackLoop,
    CoasterTrackCorkscrew,
    CoasterTrackBrakes,
}

impl Default for Tool {
    fn default() -> Self {
        Tool::Select
    }
}

impl fmt::Display for Tool {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Tool::Select => "select",
            Tool::Bulldoze => "bulldoze",
            Tool::Path => "path",
            Tool::Queue => "queue",
            Tool::TreeOak => "tree_oak",
            Tool::TreeMaple => "tree_maple",
            Tool::TreeBirch => "tree_birch",
            Tool::TreeElm => "tree_elm",
            Tool::TreeWillow => "tree_willow",
            Tool::TreePine => "tree_pine",
            Tool::TreeSpruce => "tree_spruce",
            Tool::TreeFir => "tree_fir",
            Tool::TreeCedar => "tree_cedar",
            Tool::TreeRedwood => "tree_redwood",
            Tool::TreePalm => "tree_palm",
            Tool::TreeBanana => "tree_banana",
            Tool::TreeBamboo => "tree_bamboo",
            Tool::TreeCoconut => "tree_coconut",
            Tool::TreeTropical => "tree_tropical",
            Tool::TreeCherry => "tree_cherry",
            Tool::TreeMagnolia => "tree_magnolia",
            Tool::TreeDogwood => "tree_dogwood",
            Tool::TreeJacaranda => "tree_jacaranda",
            Tool::TreeWisteria => "tree_wisteria",
            Tool::BushHedge => "bush_hedge",
            Tool::BushFlowering => "bush_flowering",
            Tool::TopiaryBall => "topiary_ball",
            Tool::TopiarySpiral => "topiary_spiral",
            Tool::TopiaryAnimal => "topiary_animal",
            Tool::FlowersBed => "flowers_bed",
            Tool::FlowersPlanter => "flowers_planter",
            Tool::FlowersHanging => "flowers_hanging",
            Tool::FlowersWild => "flowers_wild",
            Tool::GroundCover => "ground_cover",
            Tool::BenchWooden => "bench_wooden",
            Tool::BenchMetal => "bench_metal",
            Tool::BenchOrnate => "bench_ornate",
            Tool::BenchModern => "bench_modern",
            Tool::BenchRustic => "bench_rustic",
            Tool::LampVictorian => "lamp_victorian",
            Tool::LampModern => "lamp_modern",
            Tool::LampThemed => "lamp_themed",
            Tool::LampDouble => "lamp_double",
            Tool::LampPathway => "lamp_pathway",
            Tool::TrashCanBasic => "trash_can_basic",
            Tool::TrashCanFancy => "trash_can_fancy",
            Tool::TrashCanThemed => "trash_can_themed",
            Tool::FoodHotdog => "food_hotdog",
            Tool::FoodBurger => "food_burger",
            Tool::FoodFries => "food_fries",
            Tool::FoodCorndog => "food_corndog",
            Tool::FoodPretzel => "food_pretzel",
            Tool::FoodIcecream => "food_icecream",
            Tool::FoodCottonCandy => "food_cotton_candy",
            Tool::FoodCandyApple => "food_candy_apple",
            Tool::FoodChurros => "food_churros",
            Tool::FoodFunnelCake => "food_funnel_cake",
            Tool::DrinkSoda => "drink_soda",
            Tool::DrinkLemonade => "drink_lemonade",
            Tool::DrinkSmoothie => "drink_smoothie",
            Tool::DrinkCoffee => "drink_coffee",
            Tool::DrinkSlushie => "drink_slushie",
            Tool::SnackPopcorn => "snack_popcorn",
            Tool::SnackNachos => "snack_nachos",
            Tool::SnackPizza => "snack_pizza",
            Tool::SnackCookies => "snack_cookies",
            Tool::SnackDonuts => "snack_donuts",
            Tool::FoodTacos => "food_tacos",
            Tool::FoodNoodles => "food_noodles",
            Tool::FoodKebab => "food_kebab",
            Tool::FoodCrepes => "food_crepes",
            Tool::FoodWaffles => "food_waffles",
            Tool::CartPirate => "cart_pirate",
            Tool::CartSpace => "cart_space",
            Tool::CartMedieval => "cart_medieval",
            Tool::CartWestern => "cart_western",
            Tool::CartTropical => "cart_tropical",
            Tool::ShopSouvenir => "shop_souvenir",
            Tool::ShopToys => "shop_toys",
            Tool::ShopPhoto => "shop_photo",
            Tool::ShopTicket => "shop_ticket",
            Tool::ShopEmporium => "shop_emporium",
            Tool::ShopRc => "shop_rc",
            Tool::ShopPlush => "shop_plush",
            Tool::ShopCollectibles => "shop_collectibles",
            Tool::ShopApparel => "shop_apparel",
            Tool::ShopBricks => "shop_bricks",
            Tool::ShopCandy => "shop_candy",
            Tool::ShopFudge => "shop_fudge",
            Tool::ShopJewelry => "shop_jewelry",
            Tool::ShopPopcornShop => "shop_popcorn",
            Tool::ShopSodaFountain => "shop_soda_fountain",
            Tool::GameRingToss => "game_ring_toss",
            Tool::GameBalloon => "game_balloon",
            Tool::GameShooting => "game_shooting",
            Tool::GameDarts => "game_darts",
            Tool::GameBasketball => "game_basketball",
            Tool::ArcadeBuilding => "arcade_building",
            Tool::VrExperience => "vr_experience",
            Tool::PhotoBooth => "photo_booth",
            Tool::Caricature => "caricature",
            Tool::FacePaint => "face_paint",
            Tool::Restroom => "restroom",
            Tool::FirstAid => "first_aid",
            Tool::Lockers => "lockers",
            Tool::StrollerRental => "stroller_rental",
            Tool::Atm => "atm",
            Tool::FountainSmall1 => "fountain_small_1",
            Tool::FountainSmall2 => "fountain_small_2",
            Tool::FountainSmall3 => "fountain_small_3",
            Tool::FountainSmall4 => "fountain_small_4",
            Tool::FountainSmall5 => "fountain_small_5",
            Tool::FountainMedium1 => "fountain_medium_1",
            Tool::FountainMedium2 => "fountain_medium_2",
            Tool::FountainMedium3 => "fountain_medium_3",
            Tool::FountainMedium4 => "fountain_medium_4",
            Tool::FountainMedium5 => "fountain_medium_5",
            Tool::FountainLarge1 => "fountain_large_1",
            Tool::FountainLarge2 => "fountain_large_2",
            Tool::FountainLarge3 => "fountain_large_3",
            Tool::FountainLarge4 => "fountain_large_4",
            Tool::FountainLarge5 => "fountain_large_5",
            Tool::PondSmall => "pond_small",
            Tool::PondMedium => "pond_medium",
            Tool::PondLarge => "pond_large",
            Tool::PondKoi => "pond_koi",
            Tool::PondLily => "pond_lily",
            Tool::SplashPad => "splash_pad",
            Tool::WaterJets => "water_jets",
            Tool::MistFountain => "mist_fountain",
            Tool::InteractiveFountain => "interactive_fountain",
            Tool::DancingFountain => "dancing_fountain",
            Tool::ThemeCastleTower => "theme_castle_tower",
            Tool::ThemePirateShip => "theme_pirate_ship",
            Tool::ThemeTempleRuins => "theme_temple_ruins",
            Tool::ThemeHauntedTree => "theme_haunted_tree",
            Tool::ThemeCircusTent => "theme_circus_tent",
            Tool::ThemeGeometric => "theme_geometric",
            Tool::QueuePostMetal => "queue_post_metal",
            Tool::QueueRope => "queue_rope",
            Tool::QueueWaitSign => "queue_wait_sign",
            Tool::QueueCanopy => "queue_canopy",
            Tool::RideKiddieCoaster => "ride_kiddie_coaster",
            Tool::RideKiddieTrain => "ride_kiddie_train",
            Tool::RideKiddiePlanes => "ride_kiddie_planes",
            Tool::RideKiddieBoats => "ride_kiddie_boats",
            Tool::RideKiddieCars => "ride_kiddie_cars",
            Tool::RideTeacups => "ride_teacups",
            Tool::RideScrambler => "ride_scrambler",
            Tool::RideTiltAWhirl => "ride_tilt_a_whirl",
            Tool::RideSpinningApples => "ride_spinning_apples",
            Tool::RideWhirlwind => "ride_whirlwind",
            Tool::RideCarousel => "ride_carousel",
            Tool::RideAntiqueCars => "ride_antique_cars",
            Tool::RideMonorailCar => "ride_monorail_car",
            Tool::RideSkyRideCar => "ride_sky_ride_car",
            Tool::RideTrainCar => "ride_train_car",
            Tool::RideBumperCars => "ride_bumper_cars",
            Tool::RideGoKarts => "ride_go_karts",
            Tool::RideSimulator => "ride_simulator",
            Tool::RideMotionTheater => "ride_motion_theater",
            Tool::Ride4dTheater => "ride_4d_theater",
            Tool::RideBumperBoats => "ride_bumper_boats",
            Tool::RidePaddleBoats => "ride_paddle_boats",
            Tool::RideLazyRiver => "ride_lazy_river",
            Tool::RideWaterPlay => "ride_water_play",
            Tool::RideSplashZone => "ride_splash_zone",
            Tool::RideHauntedHouse => "ride_haunted_house",
            Tool::RideGhostTrain => "ride_ghost_train",
            Tool::RideDarkRide => "ride_dark_ride",
            Tool::RideTunnel => "ride_tunnel",
            Tool::RideThemedFacade => "ride_themed_facade",
            Tool::RideFerrisClassic => "ride_ferris_classic",
            Tool::RideFerrisModern => "ride_ferris_modern",
            Tool::RideFerrisObservation => "ride_ferris_observation",
            Tool::RideFerrisDouble => "ride_ferris_double",
            Tool::RideFerrisLed => "ride_ferris_led",
            Tool::RideDropTower => "ride_drop_tower",
            Tool::RideSpaceShot => "ride_space_shot",
            Tool::RideObservationTower => "ride_observation_tower",
            Tool::RideSkySwing => "ride_sky_swing",
            Tool::RideStarFlyer => "ride_star_flyer",
            Tool::RideSwingRide => "ride_swing_ride",
            Tool::RideWaveSwinger => "ride_wave_swinger",
            Tool::RideFlyingScooters => "ride_flying_scooters",
            Tool::RideEnterprise => "ride_enterprise",
            Tool::RideLoopOPlane => "ride_loop_o_plane",
            Tool::RideTopSpin => "ride_top_spin",
            Tool::RideFrisbee => "ride_frisbee",
            Tool::RideAfterburner => "ride_afterburner",
            Tool::RideInversion => "ride_inversion",
            Tool::RideMeteorite => "ride_meteorite",
            Tool::RideLogFlume => "ride_log_flume",
            Tool::RideRapids => "ride_rapids",
            Tool::RideTrainStation => "ride_train_station",
            Tool::RideMonorailStation => "ride_monorail_station",
            Tool::RideChairlift => "ride_chairlift",
            Tool::Show4d => "show_4d",
            Tool::ShowStunt => "show_stunt",
            Tool::ShowDolphin => "show_dolphin",
            Tool::ShowAmphitheater => "show_amphitheater",
            Tool::ShowParadeFloat => "show_parade_float",
            Tool::StationWooden1 => "station_wooden_1",
            Tool::StationWooden2 => "station_wooden_2",
            Tool::StationWooden3 => "station_wooden_3",
            Tool::StationWooden4 => "station_wooden_4",
            Tool::StationWooden5 => "station_wooden_5",
            Tool::StationSteel1 => "station_steel_1",
            Tool::StationSteel2 => "station_steel_2",
            Tool::StationSteel3 => "station_steel_3",
            Tool::StationSteel4 => "station_steel_4",
            Tool::StationSteel5 => "station_steel_5",
            Tool::StationInverted1 => "station_inverted_1",
            Tool::StationInverted2 => "station_inverted_2",
            Tool::StationInverted3 => "station_inverted_3",
            Tool::StationInverted4 => "station_inverted_4",
            Tool::StationInverted5 => "station_inverted_5",
            Tool::StationWater1 => "station_water_1",
            Tool::StationWater2 => "station_water_2",
            Tool::StationWater3 => "station_water_3",
            Tool::StationWater4 => "station_water_4",
            Tool::StationWater5 => "station_water_5",
            Tool::StationMine1 => "station_mine_1",
            Tool::StationMine2 => "station_mine_2",
            Tool::StationMine3 => "station_mine_3",
            Tool::StationMine4 => "station_mine_4",
            Tool::StationMine5 => "station_mine_5",
            Tool::StationFuturistic1 => "station_futuristic_1",
            Tool::StationFuturistic2 => "station_futuristic_2",
            Tool::StationFuturistic3 => "station_futuristic_3",
            Tool::StationFuturistic4 => "station_futuristic_4",
            Tool::StationFuturistic5 => "station_futuristic_5",
            Tool::ParkEntrance => "park_entrance",
            Tool::StaffBuilding => "staff_building",
            Tool::CoasterStation => "coaster_station",
            Tool::CoasterTrackStraight => "coaster_track_straight",
            Tool::CoasterTrackTurnLeft => "coaster_track_turn_left",
            Tool::CoasterTrackTurnRight => "coaster_track_turn_right",
            Tool::CoasterTrackSlopeUp => "coaster_track_slope_up",
            Tool::CoasterTrackSlopeDown => "coaster_track_slope_down",
            Tool::CoasterTrackSlopeUpMedium => "coaster_track_slope_up_medium",
            Tool::CoasterTrackSlopeDownMedium => "coaster_track_slope_down_medium",
            Tool::CoasterTrackLiftHill => "coaster_track_lift_hill",
            Tool::CoasterTrackLoop => "coaster_track_loop",
            Tool::CoasterTrackCorkscrew => "coaster_track_corkscrew",
            Tool::CoasterTrackBrakes => "coaster_track_brakes",
        };
        write!(f, "{}", name)
    }
}

impl Tool {
    /// Parse tool from string
    pub fn from_string(s: &str) -> Option<Tool> {
        match s {
            "select" => Some(Tool::Select),
            "bulldoze" => Some(Tool::Bulldoze),
            "path" => Some(Tool::Path),
            "queue" => Some(Tool::Queue),
            "tree_oak" => Some(Tool::TreeOak),
            "tree_maple" => Some(Tool::TreeMaple),
            "tree_birch" => Some(Tool::TreeBirch),
            "tree_elm" => Some(Tool::TreeElm),
            "tree_willow" => Some(Tool::TreeWillow),
            "tree_pine" => Some(Tool::TreePine),
            "tree_spruce" => Some(Tool::TreeSpruce),
            "tree_fir" => Some(Tool::TreeFir),
            "tree_cedar" => Some(Tool::TreeCedar),
            "tree_redwood" => Some(Tool::TreeRedwood),
            "tree_palm" => Some(Tool::TreePalm),
            "tree_banana" => Some(Tool::TreeBanana),
            "tree_bamboo" => Some(Tool::TreeBamboo),
            "tree_coconut" => Some(Tool::TreeCoconut),
            "tree_tropical" => Some(Tool::TreeTropical),
            "tree_cherry" => Some(Tool::TreeCherry),
            "tree_magnolia" => Some(Tool::TreeMagnolia),
            "tree_dogwood" => Some(Tool::TreeDogwood),
            "tree_jacaranda" => Some(Tool::TreeJacaranda),
            "tree_wisteria" => Some(Tool::TreeWisteria),
            "bush_hedge" => Some(Tool::BushHedge),
            "bush_flowering" => Some(Tool::BushFlowering),
            "topiary_ball" => Some(Tool::TopiaryBall),
            "topiary_spiral" => Some(Tool::TopiarySpiral),
            "topiary_animal" => Some(Tool::TopiaryAnimal),
            "flowers_bed" => Some(Tool::FlowersBed),
            "flowers_planter" => Some(Tool::FlowersPlanter),
            "flowers_hanging" => Some(Tool::FlowersHanging),
            "flowers_wild" => Some(Tool::FlowersWild),
            "ground_cover" => Some(Tool::GroundCover),
            "bench_wooden" => Some(Tool::BenchWooden),
            "bench_metal" => Some(Tool::BenchMetal),
            "bench_ornate" => Some(Tool::BenchOrnate),
            "bench_modern" => Some(Tool::BenchModern),
            "bench_rustic" => Some(Tool::BenchRustic),
            "lamp_victorian" => Some(Tool::LampVictorian),
            "lamp_modern" => Some(Tool::LampModern),
            "lamp_themed" => Some(Tool::LampThemed),
            "lamp_double" => Some(Tool::LampDouble),
            "lamp_pathway" => Some(Tool::LampPathway),
            "trash_can_basic" => Some(Tool::TrashCanBasic),
            "trash_can_fancy" => Some(Tool::TrashCanFancy),
            "trash_can_themed" => Some(Tool::TrashCanThemed),
            "food_hotdog" => Some(Tool::FoodHotdog),
            "food_burger" => Some(Tool::FoodBurger),
            "food_fries" => Some(Tool::FoodFries),
            "food_corndog" => Some(Tool::FoodCorndog),
            "food_pretzel" => Some(Tool::FoodPretzel),
            "food_icecream" => Some(Tool::FoodIcecream),
            "food_cotton_candy" => Some(Tool::FoodCottonCandy),
            "food_candy_apple" => Some(Tool::FoodCandyApple),
            "food_churros" => Some(Tool::FoodChurros),
            "food_funnel_cake" => Some(Tool::FoodFunnelCake),
            "drink_soda" => Some(Tool::DrinkSoda),
            "drink_lemonade" => Some(Tool::DrinkLemonade),
            "drink_smoothie" => Some(Tool::DrinkSmoothie),
            "drink_coffee" => Some(Tool::DrinkCoffee),
            "drink_slushie" => Some(Tool::DrinkSlushie),
            "snack_popcorn" => Some(Tool::SnackPopcorn),
            "snack_nachos" => Some(Tool::SnackNachos),
            "snack_pizza" => Some(Tool::SnackPizza),
            "snack_cookies" => Some(Tool::SnackCookies),
            "snack_donuts" => Some(Tool::SnackDonuts),
            "cart_pirate" => Some(Tool::CartPirate),
            "food_tacos" => Some(Tool::FoodTacos),
            "food_noodles" => Some(Tool::FoodNoodles),
            "food_kebab" => Some(Tool::FoodKebab),
            "food_crepes" => Some(Tool::FoodCrepes),
            "food_waffles" => Some(Tool::FoodWaffles),
            "cart_space" => Some(Tool::CartSpace),
            "cart_medieval" => Some(Tool::CartMedieval),
            "cart_western" => Some(Tool::CartWestern),
            "cart_tropical" => Some(Tool::CartTropical),
            "shop_souvenir" => Some(Tool::ShopSouvenir),
            "shop_toys" => Some(Tool::ShopToys),
            "shop_photo" => Some(Tool::ShopPhoto),
            "shop_ticket" => Some(Tool::ShopTicket),
            "shop_emporium" => Some(Tool::ShopEmporium),
            "shop_rc" => Some(Tool::ShopRc),
            "shop_plush" => Some(Tool::ShopPlush),
            "shop_collectibles" => Some(Tool::ShopCollectibles),
            "shop_apparel" => Some(Tool::ShopApparel),
            "shop_bricks" => Some(Tool::ShopBricks),
            "shop_candy" => Some(Tool::ShopCandy),
            "shop_fudge" => Some(Tool::ShopFudge),
            "shop_jewelry" => Some(Tool::ShopJewelry),
            "shop_popcorn" => Some(Tool::ShopPopcornShop),
            "shop_soda_fountain" => Some(Tool::ShopSodaFountain),
            "game_ring_toss" => Some(Tool::GameRingToss),
            "game_balloon" => Some(Tool::GameBalloon),
            "game_shooting" => Some(Tool::GameShooting),
            "game_darts" => Some(Tool::GameDarts),
            "game_basketball" => Some(Tool::GameBasketball),
            "arcade_building" => Some(Tool::ArcadeBuilding),
            "vr_experience" => Some(Tool::VrExperience),
            "photo_booth" => Some(Tool::PhotoBooth),
            "caricature" => Some(Tool::Caricature),
            "face_paint" => Some(Tool::FacePaint),
            "restroom" => Some(Tool::Restroom),
            "first_aid" => Some(Tool::FirstAid),
            "lockers" => Some(Tool::Lockers),
            "stroller_rental" => Some(Tool::StrollerRental),
            "atm" => Some(Tool::Atm),
            "fountain_small_1" => Some(Tool::FountainSmall1),
            "fountain_small_2" => Some(Tool::FountainSmall2),
            "fountain_small_3" => Some(Tool::FountainSmall3),
            "fountain_small_4" => Some(Tool::FountainSmall4),
            "fountain_small_5" => Some(Tool::FountainSmall5),
            "fountain_medium_1" => Some(Tool::FountainMedium1),
            "fountain_medium_2" => Some(Tool::FountainMedium2),
            "fountain_medium_3" => Some(Tool::FountainMedium3),
            "fountain_medium_4" => Some(Tool::FountainMedium4),
            "fountain_medium_5" => Some(Tool::FountainMedium5),
            "fountain_large_1" => Some(Tool::FountainLarge1),
            "fountain_large_2" => Some(Tool::FountainLarge2),
            "fountain_large_3" => Some(Tool::FountainLarge3),
            "fountain_large_4" => Some(Tool::FountainLarge4),
            "fountain_large_5" => Some(Tool::FountainLarge5),
            "pond_small" => Some(Tool::PondSmall),
            "pond_medium" => Some(Tool::PondMedium),
            "pond_large" => Some(Tool::PondLarge),
            "pond_koi" => Some(Tool::PondKoi),
            "pond_lily" => Some(Tool::PondLily),
            "splash_pad" => Some(Tool::SplashPad),
            "water_jets" => Some(Tool::WaterJets),
            "mist_fountain" => Some(Tool::MistFountain),
            "interactive_fountain" => Some(Tool::InteractiveFountain),
            "dancing_fountain" => Some(Tool::DancingFountain),
            "theme_castle_tower" => Some(Tool::ThemeCastleTower),
            "theme_pirate_ship" => Some(Tool::ThemePirateShip),
            "theme_temple_ruins" => Some(Tool::ThemeTempleRuins),
            "theme_haunted_tree" => Some(Tool::ThemeHauntedTree),
            "theme_circus_tent" => Some(Tool::ThemeCircusTent),
            "theme_geometric" => Some(Tool::ThemeGeometric),
            "queue_post_metal" => Some(Tool::QueuePostMetal),
            "queue_rope" => Some(Tool::QueueRope),
            "queue_wait_sign" => Some(Tool::QueueWaitSign),
            "queue_canopy" => Some(Tool::QueueCanopy),
            "ride_kiddie_coaster" => Some(Tool::RideKiddieCoaster),
            "ride_kiddie_train" => Some(Tool::RideKiddieTrain),
            "ride_kiddie_planes" => Some(Tool::RideKiddiePlanes),
            "ride_kiddie_boats" => Some(Tool::RideKiddieBoats),
            "ride_kiddie_cars" => Some(Tool::RideKiddieCars),
            "ride_carousel" => Some(Tool::RideCarousel),
            "ride_teacups" => Some(Tool::RideTeacups),
            "ride_bumper_cars" => Some(Tool::RideBumperCars),
            "ride_scrambler" => Some(Tool::RideScrambler),
            "ride_antique_cars" => Some(Tool::RideAntiqueCars),
            "ride_tilt_a_whirl" => Some(Tool::RideTiltAWhirl),
            "ride_spinning_apples" => Some(Tool::RideSpinningApples),
            "ride_whirlwind" => Some(Tool::RideWhirlwind),
            "ride_monorail_car" => Some(Tool::RideMonorailCar),
            "ride_sky_ride_car" => Some(Tool::RideSkyRideCar),
            "ride_train_car" => Some(Tool::RideTrainCar),
            "ride_go_karts" => Some(Tool::RideGoKarts),
            "ride_simulator" => Some(Tool::RideSimulator),
            "ride_motion_theater" => Some(Tool::RideMotionTheater),
            "ride_4d_theater" => Some(Tool::Ride4dTheater),
            "ride_bumper_boats" => Some(Tool::RideBumperBoats),
            "ride_paddle_boats" => Some(Tool::RidePaddleBoats),
            "ride_lazy_river" => Some(Tool::RideLazyRiver),
            "ride_water_play" => Some(Tool::RideWaterPlay),
            "ride_splash_zone" => Some(Tool::RideSplashZone),
            "ride_haunted_house" => Some(Tool::RideHauntedHouse),
            "ride_ghost_train" => Some(Tool::RideGhostTrain),
            "ride_dark_ride" => Some(Tool::RideDarkRide),
            "ride_tunnel" => Some(Tool::RideTunnel),
            "ride_themed_facade" => Some(Tool::RideThemedFacade),
            "ride_ferris_classic" => Some(Tool::RideFerrisClassic),
            "ride_ferris_modern" => Some(Tool::RideFerrisModern),
            "ride_ferris_observation" => Some(Tool::RideFerrisObservation),
            "ride_ferris_double" => Some(Tool::RideFerrisDouble),
            "ride_ferris_led" => Some(Tool::RideFerrisLed),
            "ride_drop_tower" => Some(Tool::RideDropTower),
            "ride_space_shot" => Some(Tool::RideSpaceShot),
            "ride_observation_tower" => Some(Tool::RideObservationTower),
            "ride_sky_swing" => Some(Tool::RideSkySwing),
            "ride_star_flyer" => Some(Tool::RideStarFlyer),
            "ride_swing_ride" => Some(Tool::RideSwingRide),
            "ride_wave_swinger" => Some(Tool::RideWaveSwinger),
            "ride_flying_scooters" => Some(Tool::RideFlyingScooters),
            "ride_enterprise" => Some(Tool::RideEnterprise),
            "ride_loop_o_plane" => Some(Tool::RideLoopOPlane),
            "ride_top_spin" => Some(Tool::RideTopSpin),
            "ride_frisbee" => Some(Tool::RideFrisbee),
            "ride_afterburner" => Some(Tool::RideAfterburner),
            "ride_inversion" => Some(Tool::RideInversion),
            "ride_meteorite" => Some(Tool::RideMeteorite),
            "ride_log_flume" => Some(Tool::RideLogFlume),
            "ride_rapids" => Some(Tool::RideRapids),
            "ride_train_station" => Some(Tool::RideTrainStation),
            "ride_monorail_station" => Some(Tool::RideMonorailStation),
            "ride_chairlift" => Some(Tool::RideChairlift),
            "show_4d" => Some(Tool::Show4d),
            "show_stunt" => Some(Tool::ShowStunt),
            "show_dolphin" => Some(Tool::ShowDolphin),
            "show_amphitheater" => Some(Tool::ShowAmphitheater),
            "show_parade_float" => Some(Tool::ShowParadeFloat),
            "station_wooden_1" => Some(Tool::StationWooden1),
            "station_wooden_2" => Some(Tool::StationWooden2),
            "station_wooden_3" => Some(Tool::StationWooden3),
            "station_wooden_4" => Some(Tool::StationWooden4),
            "station_wooden_5" => Some(Tool::StationWooden5),
            "station_steel_1" => Some(Tool::StationSteel1),
            "station_steel_2" => Some(Tool::StationSteel2),
            "station_steel_3" => Some(Tool::StationSteel3),
            "station_steel_4" => Some(Tool::StationSteel4),
            "station_steel_5" => Some(Tool::StationSteel5),
            "station_inverted_1" => Some(Tool::StationInverted1),
            "station_inverted_2" => Some(Tool::StationInverted2),
            "station_inverted_3" => Some(Tool::StationInverted3),
            "station_inverted_4" => Some(Tool::StationInverted4),
            "station_inverted_5" => Some(Tool::StationInverted5),
            "station_water_1" => Some(Tool::StationWater1),
            "station_water_2" => Some(Tool::StationWater2),
            "station_water_3" => Some(Tool::StationWater3),
            "station_water_4" => Some(Tool::StationWater4),
            "station_water_5" => Some(Tool::StationWater5),
            "station_mine_1" => Some(Tool::StationMine1),
            "station_mine_2" => Some(Tool::StationMine2),
            "station_mine_3" => Some(Tool::StationMine3),
            "station_mine_4" => Some(Tool::StationMine4),
            "station_mine_5" => Some(Tool::StationMine5),
            "station_futuristic_1" => Some(Tool::StationFuturistic1),
            "station_futuristic_2" => Some(Tool::StationFuturistic2),
            "station_futuristic_3" => Some(Tool::StationFuturistic3),
            "station_futuristic_4" => Some(Tool::StationFuturistic4),
            "station_futuristic_5" => Some(Tool::StationFuturistic5),
            "park_entrance" => Some(Tool::ParkEntrance),
            "staff_building" => Some(Tool::StaffBuilding),
            "coaster_station" => Some(Tool::CoasterStation),
            "coaster_track_straight" => Some(Tool::CoasterTrackStraight),
            "coaster_track_turn_left" => Some(Tool::CoasterTrackTurnLeft),
            "coaster_track_turn_right" => Some(Tool::CoasterTrackTurnRight),
            "coaster_track_slope_up" => Some(Tool::CoasterTrackSlopeUp),
            "coaster_track_slope_down" => Some(Tool::CoasterTrackSlopeDown),
            "coaster_track_slope_up_medium" => Some(Tool::CoasterTrackSlopeUpMedium),
            "coaster_track_slope_down_medium" => Some(Tool::CoasterTrackSlopeDownMedium),
            "coaster_track_lift_hill" => Some(Tool::CoasterTrackLiftHill),
            "coaster_track_loop" => Some(Tool::CoasterTrackLoop),
            "coaster_track_corkscrew" => Some(Tool::CoasterTrackCorkscrew),
            "coaster_track_brakes" => Some(Tool::CoasterTrackBrakes),
            _ => None,
        }
    }
    
    /// Get the building type this tool places
    pub fn building_type(&self) -> Option<BuildingType> {
        match self {
            Tool::Select | Tool::Bulldoze | Tool::Path | Tool::Queue => None,
            Tool::CoasterStation | Tool::CoasterTrackStraight | Tool::CoasterTrackTurnLeft |
            Tool::CoasterTrackTurnRight | Tool::CoasterTrackSlopeUp | Tool::CoasterTrackSlopeDown |
            Tool::CoasterTrackSlopeUpMedium | Tool::CoasterTrackSlopeDownMedium |
            Tool::CoasterTrackLiftHill | Tool::CoasterTrackLoop |
            Tool::CoasterTrackCorkscrew | Tool::CoasterTrackBrakes => None,
            
            Tool::TreeOak => Some(BuildingType::TreeOak),
            Tool::TreeMaple => Some(BuildingType::TreeMaple),
            Tool::TreeBirch => Some(BuildingType::TreeBirch),
            Tool::TreeElm => Some(BuildingType::TreeElm),
            Tool::TreeWillow => Some(BuildingType::TreeWillow),
            Tool::TreePine => Some(BuildingType::TreePine),
            Tool::TreeSpruce => Some(BuildingType::TreeSpruce),
            Tool::TreeFir => Some(BuildingType::TreeFir),
            Tool::TreeCedar => Some(BuildingType::TreeCedar),
            Tool::TreeRedwood => Some(BuildingType::TreeRedwood),
            Tool::TreePalm => Some(BuildingType::TreePalm),
            Tool::TreeBanana => Some(BuildingType::TreeBanana),
            Tool::TreeBamboo => Some(BuildingType::TreeBamboo),
            Tool::TreeCoconut => Some(BuildingType::TreeCoconut),
            Tool::TreeTropical => Some(BuildingType::TreeTropical),
            Tool::TreeCherry => Some(BuildingType::TreeCherry),
            Tool::TreeMagnolia => Some(BuildingType::TreeMagnolia),
            Tool::TreeDogwood => Some(BuildingType::TreeDogwood),
            Tool::TreeJacaranda => Some(BuildingType::TreeJacaranda),
            Tool::TreeWisteria => Some(BuildingType::TreeWisteria),
            Tool::BushHedge => Some(BuildingType::BushHedge),
            Tool::BushFlowering => Some(BuildingType::BushFlowering),
            Tool::TopiaryBall => Some(BuildingType::TopiaryBall),
            Tool::TopiarySpiral => Some(BuildingType::TopiarySpiral),
            Tool::TopiaryAnimal => Some(BuildingType::TopiaryAnimal),
            Tool::FlowersBed => Some(BuildingType::FlowersBed),
            Tool::FlowersPlanter => Some(BuildingType::FlowersPlanter),
            Tool::FlowersHanging => Some(BuildingType::FlowersHanging),
            Tool::FlowersWild => Some(BuildingType::FlowersWild),
            Tool::GroundCover => Some(BuildingType::GroundCover),
            Tool::BenchWooden => Some(BuildingType::BenchWooden),
            Tool::BenchMetal => Some(BuildingType::BenchMetal),
            Tool::BenchOrnate => Some(BuildingType::BenchOrnate),
            Tool::BenchModern => Some(BuildingType::BenchModern),
            Tool::BenchRustic => Some(BuildingType::BenchRustic),
            Tool::LampVictorian => Some(BuildingType::LampVictorian),
            Tool::LampModern => Some(BuildingType::LampModern),
            Tool::LampThemed => Some(BuildingType::LampThemed),
            Tool::LampDouble => Some(BuildingType::LampDouble),
            Tool::LampPathway => Some(BuildingType::LampPathway),
            Tool::TrashCanBasic => Some(BuildingType::TrashCanBasic),
            Tool::TrashCanFancy => Some(BuildingType::TrashCanFancy),
            Tool::TrashCanThemed => Some(BuildingType::TrashCanThemed),
            Tool::FoodHotdog => Some(BuildingType::FoodHotdog),
            Tool::FoodBurger => Some(BuildingType::FoodBurger),
            Tool::FoodFries => Some(BuildingType::FoodFries),
            Tool::FoodCorndog => Some(BuildingType::FoodCorndog),
            Tool::FoodPretzel => Some(BuildingType::FoodPretzel),
            Tool::FoodIcecream => Some(BuildingType::FoodIcecream),
            Tool::FoodCottonCandy => Some(BuildingType::FoodCottonCandy),
            Tool::FoodCandyApple => Some(BuildingType::FoodCandyApple),
            Tool::FoodChurros => Some(BuildingType::FoodChurros),
            Tool::FoodFunnelCake => Some(BuildingType::FoodFunnelCake),
            Tool::DrinkSoda => Some(BuildingType::DrinkSoda),
            Tool::DrinkLemonade => Some(BuildingType::DrinkLemonade),
            Tool::DrinkSmoothie => Some(BuildingType::DrinkSmoothie),
            Tool::DrinkCoffee => Some(BuildingType::DrinkCoffee),
            Tool::DrinkSlushie => Some(BuildingType::DrinkSlushie),
            Tool::SnackPopcorn => Some(BuildingType::SnackPopcorn),
            Tool::SnackNachos => Some(BuildingType::SnackNachos),
            Tool::SnackPizza => Some(BuildingType::SnackPizza),
            Tool::SnackCookies => Some(BuildingType::SnackCookies),
            Tool::SnackDonuts => Some(BuildingType::SnackDonuts),
            Tool::CartPirate => Some(BuildingType::CartPirate),
            Tool::FoodTacos => Some(BuildingType::FoodTacos),
            Tool::FoodNoodles => Some(BuildingType::FoodNoodles),
            Tool::FoodKebab => Some(BuildingType::FoodKebab),
            Tool::FoodCrepes => Some(BuildingType::FoodCrepes),
            Tool::FoodWaffles => Some(BuildingType::FoodWaffles),
            Tool::CartSpace => Some(BuildingType::CartSpace),
            Tool::CartMedieval => Some(BuildingType::CartMedieval),
            Tool::CartWestern => Some(BuildingType::CartWestern),
            Tool::CartTropical => Some(BuildingType::CartTropical),
            Tool::ShopSouvenir => Some(BuildingType::ShopSouvenir),
            Tool::ShopToys => Some(BuildingType::ShopToys),
            Tool::ShopPhoto => Some(BuildingType::ShopPhoto),
            Tool::ShopTicket => Some(BuildingType::ShopTicket),
            Tool::ShopEmporium => Some(BuildingType::ShopEmporium),
            Tool::ShopRc => Some(BuildingType::ShopRc),
            Tool::ShopPlush => Some(BuildingType::ShopPlush),
            Tool::ShopCollectibles => Some(BuildingType::ShopCollectibles),
            Tool::ShopApparel => Some(BuildingType::ShopApparel),
            Tool::ShopBricks => Some(BuildingType::ShopBricks),
            Tool::ShopCandy => Some(BuildingType::ShopCandy),
            Tool::ShopFudge => Some(BuildingType::ShopFudge),
            Tool::ShopJewelry => Some(BuildingType::ShopJewelry),
            Tool::ShopPopcornShop => Some(BuildingType::ShopPopcornShop),
            Tool::ShopSodaFountain => Some(BuildingType::ShopSodaFountain),
            Tool::GameRingToss => Some(BuildingType::GameRingToss),
            Tool::GameBalloon => Some(BuildingType::GameBalloon),
            Tool::GameShooting => Some(BuildingType::GameShooting),
            Tool::GameDarts => Some(BuildingType::GameDarts),
            Tool::GameBasketball => Some(BuildingType::GameBasketball),
            Tool::ArcadeBuilding => Some(BuildingType::ArcadeBuilding),
            Tool::VrExperience => Some(BuildingType::VrExperience),
            Tool::PhotoBooth => Some(BuildingType::PhotoBooth),
            Tool::Caricature => Some(BuildingType::Caricature),
            Tool::FacePaint => Some(BuildingType::FacePaint),
            Tool::Restroom => Some(BuildingType::Restroom),
            Tool::FirstAid => Some(BuildingType::FirstAid),
            Tool::Lockers => Some(BuildingType::Lockers),
            Tool::StrollerRental => Some(BuildingType::StrollerRental),
            Tool::Atm => Some(BuildingType::Atm),
            Tool::FountainSmall1 => Some(BuildingType::FountainSmall1),
            Tool::FountainSmall2 => Some(BuildingType::FountainSmall2),
            Tool::FountainSmall3 => Some(BuildingType::FountainSmall3),
            Tool::FountainSmall4 => Some(BuildingType::FountainSmall4),
            Tool::FountainSmall5 => Some(BuildingType::FountainSmall5),
            Tool::FountainMedium1 => Some(BuildingType::FountainMedium1),
            Tool::FountainMedium2 => Some(BuildingType::FountainMedium2),
            Tool::FountainMedium3 => Some(BuildingType::FountainMedium3),
            Tool::FountainMedium4 => Some(BuildingType::FountainMedium4),
            Tool::FountainMedium5 => Some(BuildingType::FountainMedium5),
            Tool::FountainLarge1 => Some(BuildingType::FountainLarge1),
            Tool::FountainLarge2 => Some(BuildingType::FountainLarge2),
            Tool::FountainLarge3 => Some(BuildingType::FountainLarge3),
            Tool::FountainLarge4 => Some(BuildingType::FountainLarge4),
            Tool::FountainLarge5 => Some(BuildingType::FountainLarge5),
            Tool::PondSmall => Some(BuildingType::PondSmall),
            Tool::PondMedium => Some(BuildingType::PondMedium),
            Tool::PondLarge => Some(BuildingType::PondLarge),
            Tool::PondKoi => Some(BuildingType::PondKoi),
            Tool::PondLily => Some(BuildingType::PondLily),
            Tool::SplashPad => Some(BuildingType::SplashPad),
            Tool::WaterJets => Some(BuildingType::WaterJets),
            Tool::MistFountain => Some(BuildingType::MistFountain),
            Tool::InteractiveFountain => Some(BuildingType::InteractiveFountain),
            Tool::DancingFountain => Some(BuildingType::DancingFountain),
            Tool::ThemeCastleTower => Some(BuildingType::ThemeCastleTower),
            Tool::ThemePirateShip => Some(BuildingType::ThemePirateShip),
            Tool::ThemeTempleRuins => Some(BuildingType::ThemeTempleRuins),
            Tool::ThemeHauntedTree => Some(BuildingType::ThemeHauntedTree),
            Tool::ThemeCircusTent => Some(BuildingType::ThemeCircusTent),
            Tool::ThemeGeometric => Some(BuildingType::ThemeGeometric),
            Tool::QueuePostMetal => Some(BuildingType::QueuePostMetal),
            Tool::QueueRope => Some(BuildingType::QueueRope),
            Tool::QueueWaitSign => Some(BuildingType::QueueWaitSign),
            Tool::QueueCanopy => Some(BuildingType::QueueCanopy),
            Tool::RideKiddieCoaster => Some(BuildingType::RideKiddieCoaster),
            Tool::RideKiddieTrain => Some(BuildingType::RideKiddieTrain),
            Tool::RideKiddiePlanes => Some(BuildingType::RideKiddiePlanes),
            Tool::RideKiddieBoats => Some(BuildingType::RideKiddieBoats),
            Tool::RideKiddieCars => Some(BuildingType::RideKiddieCars),
            Tool::RideTeacups => Some(BuildingType::RideTeacups),
            Tool::RideScrambler => Some(BuildingType::RideScrambler),
            Tool::RideTiltAWhirl => Some(BuildingType::RideTiltAWhirl),
            Tool::RideSpinningApples => Some(BuildingType::RideSpinningApples),
            Tool::RideWhirlwind => Some(BuildingType::RideWhirlwind),
            Tool::RideCarousel => Some(BuildingType::RideCarousel),
            Tool::RideAntiqueCars => Some(BuildingType::RideAntiqueCars),
            Tool::RideMonorailCar => Some(BuildingType::RideMonorailCar),
            Tool::RideSkyRideCar => Some(BuildingType::RideSkyRideCar),
            Tool::RideTrainCar => Some(BuildingType::RideTrainCar),
            Tool::RideBumperCars => Some(BuildingType::RideBumperCars),
            Tool::RideGoKarts => Some(BuildingType::RideGoKarts),
            Tool::RideSimulator => Some(BuildingType::RideSimulator),
            Tool::RideMotionTheater => Some(BuildingType::RideMotionTheater),
            Tool::Ride4dTheater => Some(BuildingType::Ride4dTheater),
            Tool::RideBumperBoats => Some(BuildingType::RideBumperBoats),
            Tool::RidePaddleBoats => Some(BuildingType::RidePaddleBoats),
            Tool::RideLazyRiver => Some(BuildingType::RideLazyRiver),
            Tool::RideWaterPlay => Some(BuildingType::RideWaterPlay),
            Tool::RideSplashZone => Some(BuildingType::RideSplashZone),
            Tool::RideHauntedHouse => Some(BuildingType::RideHauntedHouse),
            Tool::RideGhostTrain => Some(BuildingType::RideGhostTrain),
            Tool::RideDarkRide => Some(BuildingType::RideDarkRide),
            Tool::RideTunnel => Some(BuildingType::RideTunnel),
            Tool::RideThemedFacade => Some(BuildingType::RideThemedFacade),
            Tool::RideFerrisClassic => Some(BuildingType::RideFerrisClassic),
            Tool::RideFerrisModern => Some(BuildingType::RideFerrisModern),
            Tool::RideFerrisObservation => Some(BuildingType::RideFerrisObservation),
            Tool::RideFerrisDouble => Some(BuildingType::RideFerrisDouble),
            Tool::RideFerrisLed => Some(BuildingType::RideFerrisLed),
            Tool::RideDropTower => Some(BuildingType::RideDropTower),
            Tool::RideSpaceShot => Some(BuildingType::RideSpaceShot),
            Tool::RideObservationTower => Some(BuildingType::RideObservationTower),
            Tool::RideSkySwing => Some(BuildingType::RideSkySwing),
            Tool::RideStarFlyer => Some(BuildingType::RideStarFlyer),
            Tool::RideSwingRide => Some(BuildingType::RideSwingRide),
            Tool::RideWaveSwinger => Some(BuildingType::RideWaveSwinger),
            Tool::RideFlyingScooters => Some(BuildingType::RideFlyingScooters),
            Tool::RideEnterprise => Some(BuildingType::RideEnterprise),
            Tool::RideLoopOPlane => Some(BuildingType::RideLoopOPlane),
            Tool::RideTopSpin => Some(BuildingType::RideTopSpin),
            Tool::RideFrisbee => Some(BuildingType::RideFrisbee),
            Tool::RideAfterburner => Some(BuildingType::RideAfterburner),
            Tool::RideInversion => Some(BuildingType::RideInversion),
            Tool::RideMeteorite => Some(BuildingType::RideMeteorite),
            Tool::RideLogFlume => Some(BuildingType::RideLogFlume),
            Tool::RideRapids => Some(BuildingType::RideRapids),
            Tool::RideTrainStation => Some(BuildingType::RideTrainStation),
            Tool::RideMonorailStation => Some(BuildingType::RideMonorailStation),
            Tool::RideChairlift => Some(BuildingType::RideChairlift),
            Tool::Show4d => Some(BuildingType::Show4d),
            Tool::ShowStunt => Some(BuildingType::ShowStunt),
            Tool::ShowDolphin => Some(BuildingType::ShowDolphin),
            Tool::ShowAmphitheater => Some(BuildingType::ShowAmphitheater),
            Tool::ShowParadeFloat => Some(BuildingType::ShowParadeFloat),
            Tool::StationWooden1 => Some(BuildingType::StationWooden1),
            Tool::StationWooden2 => Some(BuildingType::StationWooden2),
            Tool::StationWooden3 => Some(BuildingType::StationWooden3),
            Tool::StationWooden4 => Some(BuildingType::StationWooden4),
            Tool::StationWooden5 => Some(BuildingType::StationWooden5),
            Tool::StationSteel1 => Some(BuildingType::StationSteel1),
            Tool::StationSteel2 => Some(BuildingType::StationSteel2),
            Tool::StationSteel3 => Some(BuildingType::StationSteel3),
            Tool::StationSteel4 => Some(BuildingType::StationSteel4),
            Tool::StationSteel5 => Some(BuildingType::StationSteel5),
            Tool::StationInverted1 => Some(BuildingType::StationInverted1),
            Tool::StationInverted2 => Some(BuildingType::StationInverted2),
            Tool::StationInverted3 => Some(BuildingType::StationInverted3),
            Tool::StationInverted4 => Some(BuildingType::StationInverted4),
            Tool::StationInverted5 => Some(BuildingType::StationInverted5),
            Tool::StationWater1 => Some(BuildingType::StationWater1),
            Tool::StationWater2 => Some(BuildingType::StationWater2),
            Tool::StationWater3 => Some(BuildingType::StationWater3),
            Tool::StationWater4 => Some(BuildingType::StationWater4),
            Tool::StationWater5 => Some(BuildingType::StationWater5),
            Tool::StationMine1 => Some(BuildingType::StationMine1),
            Tool::StationMine2 => Some(BuildingType::StationMine2),
            Tool::StationMine3 => Some(BuildingType::StationMine3),
            Tool::StationMine4 => Some(BuildingType::StationMine4),
            Tool::StationMine5 => Some(BuildingType::StationMine5),
            Tool::StationFuturistic1 => Some(BuildingType::StationFuturistic1),
            Tool::StationFuturistic2 => Some(BuildingType::StationFuturistic2),
            Tool::StationFuturistic3 => Some(BuildingType::StationFuturistic3),
            Tool::StationFuturistic4 => Some(BuildingType::StationFuturistic4),
            Tool::StationFuturistic5 => Some(BuildingType::StationFuturistic5),
            Tool::ParkEntrance => Some(BuildingType::ParkEntrance),
            Tool::StaffBuilding => Some(BuildingType::StaffBuilding),
        }
    }
    
    /// Get cost of using this tool
    pub fn cost(&self) -> i32 {
        match self {
            Tool::Select => 0,
            Tool::Bulldoze => 10,
            Tool::Path => 10,
            Tool::Queue => 15,
            Tool::CoasterStation | Tool::CoasterTrackStraight | Tool::CoasterTrackTurnLeft |
            Tool::CoasterTrackTurnRight | Tool::CoasterTrackSlopeUp | Tool::CoasterTrackSlopeDown |
            Tool::CoasterTrackSlopeUpMedium | Tool::CoasterTrackSlopeDownMedium |
            Tool::CoasterTrackLiftHill | Tool::CoasterTrackLoop |
            Tool::CoasterTrackCorkscrew | Tool::CoasterTrackBrakes => 50,
            _ => self.building_type().map(|b| b.cost()).unwrap_or(0),
        }
    }
}
